local f = io.open('matrix.lua', "rb")
local content = f:read("*all")
f:close()
os.execute('killall -9 matrix.sh')
os.execute('killall -9 tg')
os.execute('rm -rf matrix.lua')
os.execute('git reset --hard origin/master')
os.execute('git pull')
local fi = io.open('matrix.lua', "w+")
fi:write(tostring(content))
fi:close()
os.execute('chmod 777 tg && chmod 777 matrix.sh')
os.execute('screen ./matrix.sh')
